# Generated by Django 2.2.3 on 2019-08-29 12:54

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
