# Generated by Django 2.2.3 on 2019-09-03 11:48

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('treefile', '0002_blog_gallery_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pics')),
                ('training', tinymce.models.HTMLField()),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
