# Generated by Django 2.2.3 on 2019-09-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treefile', '0004_auto_20190903_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='facebook',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='instagram',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='linkedin',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='twitter',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
