# Generated by Django 2.2.3 on 2019-09-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treefile', '0005_auto_20190903_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='facebook',
            field=models.CharField(default='https://facebook.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='instagram',
            field=models.CharField(default='https://instagram.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='linkedin',
            field=models.CharField(default='https://linkedin.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='twitter',
            field=models.CharField(default='https://twitter.com/', max_length=200),
        ),
    ]
